version: '3.7'
services:
  app:
    build: .
    container_name: diet-tracker-back
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 4000:4000
      - 9229:9229
    command: npm run start:dev
    env_file:
      - .env

  mongo:
    image: mongo
    container_name: diet-tracker-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ADMIN_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ADMIN_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
      MONGO_USERNAME: ${MONGO_APP_USERNAME}
      MONGO_PASSWORD: ${MONGO_APP_PASSWORD}
    volumes:
      - data-volume:/data/db
      - ./mongo/init-scripts/dev:/docker-entrypoint-initdb.d
    ports:
      - 27017:27017

  gcloud-backup:
    build: 
      context: .
      dockerfile: backup.Dockerfile
    container_name: diet-tracker-backup
    environment:
      - SVC_ACCOUNT_FILE=/run/secrets/svc_account.json
    secrets:
      - svc_account.json
    command: sh -c "./setup-gcloud.sh && ./backup.sh"
    env_file:
      - .env
    depends_on:
      - mongo

volumes:
  data-volume:

secrets:
  svc_account.json:
    file: ./gcloud/certs/svc_account.json