version: '3'
services:
  app:
    build: .
    container_name: diet-tracker-back
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 4000:4000
      - 9229:9229
    command: npm run start:dev
    env_file:
      - .env
  db:
    image: couchdb:latest
    container_name: diet-tracker-db
    volumes:
      - ./couchdb/data:/opt/couchdb/data
    ports:
      - 5984:5984