version: '3'
services:
  app:
    image: jetpackpony/diet-tracker-back
    container_name: diet-tracker-back
    restart: always
    expose:
      - 3000
    env_file:
      - .env.prod
    command: npm run start:prod