version: '3.7'
services:
  app:
    image: diet-tracker-back
    container_name: diet-tracker-back
    restart: always
    networks:
      - default
    expose:
      - 4000
    ports:
      - 4000:4000
    env_file:
      - .env
    command: npm run start:prod
    depends_on:
      - mongo

  backups:
    image: diet-tracker-back
    container_name: diet-tracker-backups
    restart: always
    networks:
      - default
    environment:
      - SVC_ACCOUNT_FILE=/run/secrets/svc_account.json
    secrets:
      - svc_account.json
    env_file:
      - .env
    command: npm run backup:prod
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0
    container_name: diet-tracker-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ADMIN_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ADMIN_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
      MONGO_USERNAME: ${MONGO_APP_USERNAME}
      MONGO_PASSWORD: ${MONGO_APP_PASSWORD}
    volumes:
      - diet-tracker-data-volume:/data/db
      - ./mongo/init-scripts/dev:/docker-entrypoint-initdb.d
    expose:
      - 27017
    ports:
      - 27017:27017

volumes:
  diet-tracker-data-volume:

secrets:
  svc_account.json:
    file: .secrets/svc_account.json