version: '3.7'
services:
  app:
    image: jetpackpony/diet-tracker-back
    container_name: diet-tracker-back
    restart: always
    networks:
      - web
      - default
    expose:
      - 4000
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${VIRTUAL_HOST}"
      - "traefik.port=4000"
      - "traefik.protocol=http"
    env_file:
      - .env
    command: npm run start:prod
    depends_on:
      - mongo

  backups:
    image: jetpackpony/diet-tracker-back
    container_name: diet-tracker-backups
    restart: always
    environment:
      - SVC_ACCOUNT_FILE=/run/secrets/svc_account.json
    secrets:
      - svc_account.json
    env_file:
      - .env
    command: npm run backup:prod
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0
    container_name: diet-tracker-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ADMIN_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ADMIN_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
      MONGO_USERNAME: ${MONGO_APP_USERNAME}
      MONGO_PASSWORD: ${MONGO_APP_PASSWORD}
    volumes:
      - diet-tracker-data-volume:/data/db
      - ./mongo/init-scripts/dev:/docker-entrypoint-initdb.d
    expose:
      - 27017

volumes:
  diet-tracker-data-volume:

networks:
  web:
    external: true

secrets:
  svc_account.json:
    file: ./svc_account.json