version: '3.7'
services:
  app:
    image: jetpackpony/diet-tracker-back
    container_name: diet-tracker-back
    restart: always
    networks:
      - web
      - default
    expose:
      - 4000
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.dietTracker_insecure.rule=Host(`${VIRTUAL_HOST}`)"
      - "traefik.http.routers.dietTracker_insecure.entrypoints=web"
      - "traefik.http.routers.dietTracker_insecure.middlewares=https_redirect"

      - "traefik.http.routers.dietTracker.rule=Host(`${VIRTUAL_HOST}`)"
      - "traefik.http.routers.dietTracker.entrypoints=websecure"
      - "traefik.http.routers.dietTracker.tls.certresolver=myresolver"

      - "traefik.http.middlewares.https_redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.https_redirect.redirectscheme.permanent=true"

    env_file:
      - .env
    command: npm run start:prod
    depends_on:
      - mongo

  backups:
    image: jetpackpony/diet-tracker-back
    container_name: diet-tracker-backups
    restart: always
    environment:
      - SVC_ACCOUNT_FILE=/run/secrets/svc_account.json
    secrets:
      - svc_account.json
    env_file:
      - .env
    command: npm run backup:prod
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0
    container_name: diet-tracker-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ADMIN_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ADMIN_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
      MONGO_USERNAME: ${MONGO_APP_USERNAME}
      MONGO_PASSWORD: ${MONGO_APP_PASSWORD}
    volumes:
      - diet-tracker-data-volume:/data/db
      - ./mongo/init-scripts/dev:/docker-entrypoint-initdb.d
    expose:
      - 27017

volumes:
  diet-tracker-data-volume:

networks:
  web:
    external: true

secrets:
  svc_account.json:
    file: ./svc_account.json